
CREATE TABLE MEMBER
(
	MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '会員ID',
	MAIL_ADDRESS VARCHAR(250) NOT NULL UNIQUE COMMENT 'メールアドレス',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = '会員';


CREATE TABLE MEMBER_SECURITY
(
	MEMBER_ID BIGINT NOT NULL UNIQUE COMMENT '会員ID',
	PASSWORD VARCHAR(20) NOT NULL COMMENT 'パスワード'
) COMMENT = '会員セキュリティ情報';


CREATE TABLE TWEET
(
	TWEET_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ツイートイD',
	MESSAGE VARCHAR(140) NOT NULL COMMENT 'めっせーじ',
	MEMBER_ID BIGINT NOT NULL COMMENT '会員ID',
	PRIMARY KEY (TWEET_ID)
) COMMENT = 'ツイート';



/* Create Foreign Keys */

ALTER TABLE MEMBER_SECURITY
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



